from __future__ import annotations

COMMON_PREFIXES = {
    "WS", "LK", "LS", "DFH", "SQL", "TMP", "TEMP", "IX", "IDX", "SW"
}

ABBREVIATIONS = {
    "CUST": "customer",
    "CLI": "client",
    "CTR": "dossier",
    "ACCT": "account",
    "ACC": "account",
    "AMT": "montant",
    "MNT": "montant",
    "TOT": "total",
    "TTL": "total",
    "DT": "date",
    "DAT": "date",
    "EFF": "effective",
    "EXP": "expiration",
    "NBR": "number",
    "NB": "number",
    "CNT": "count",
    "QTY": "quantity",
    "CD": "code",
    "COD": "code",
    "DOS": "dossier",
    "DSC": "description",
    "DOSS": "dossier",
    "DESC": "description",
    "DSCR": "description",
    "VLD": "valide",
    "FIS": "fiscalité",
    "REFINT": "reference interne",
    "REFEXT": "reference externe",
    "REF": "reference",
    "REM": "remise",
    "TYP": "type",
    "TIERS": "tiers",
    "CLT": "client",
    "CESS": "cession",
    "FDD": "fiscalité par durée de détention",
    "EOC": "Euroclear",
    "INT": "interne",
    "PVAL": "plus value",
    "PV": "plus value",
    "MVAL": "moins value",
    "MV": "moins value",
    "OLD": "ancien",
    "TDOS": "dossier titres",
    "PEA": "plan d'épargne en actions",
    "PEE": "plan d'épargne entreprise",
    "TARGO": "targobank",
    "BEO": "beobank",
    "CMT": "crédit mutuel titres",
    "CIC": "cic",
    "MS": "market solutions",
    "TTMCOI": "copie messages",
    "LTNV": "copie micro",
    "EOF": "fin de fichier",
    "LEU": "lecture unique",
    "LES": "lecture suivante",
    "LEI": "ouverture curseur",
    "LEF": "fermeture curseur",
    "PRX": "prix",
    "PRU": "prix revient unitaire",
    "PRG": "prix de revient global",
    "DDV": "droits de votes",
    "CODE": "code",
    "LBL": "libellé",
    "LIB": "label",
    "STS": "status",
    "STAT": "status",
    "FLG": "flag",
    "FLAG": "flag",
    "IND": "indicator",
    "MSG": "message",
    "ADDR": "address",
    "TEL": "telephone",
    "RET": "return",
    "RC": "return_code",
    "ID": "identifier",
    "KEY": "key",
    "NAME": "name",
    "RATE": "rate",
    "PRICE": "price",
    "BAL": "balance",
    "FILE": "file",
    "REC": "record",
}

ROLE_KEYWORDS = {
    "identifier": {"identifier", "key", "id"},
    "status": {"status", "flag", "indicator"},
    "amount": {"amount", "total", "balance", "price", "rate"},
    "date": {"date", "effective", "expiration"},
    "counter": {"count", "number", "quantity"},
    "message": {"message", "label", "description", "name"},
    "io_record": {"record", "file"},
}
